### PR TITLE
fix(prisma): Avoid crash if Prisma schema path is not specified

### LINKED ISSUE #1463: 🐛 Error with lint-staged and Prisma: input.specifier.startsWith is not a function
### Prerequisites

- [x] I'm using the latest version
- [x] I've read the relevant [documentation](https://knip.dev)
- [x] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [x] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [x] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://stackblitz.com/edit/github-qrpmgdzo-zgascumc?file=package.json

### Reproduction access

- [x] I've made sure the reproduction is publicly accessible

### Description of the issue

In Knip v5.80.2, I get an error when running Knip in my project. This issue didn't happen in v5.80.1.

Here's the PR where it is happening in my project: https://github.com/stephenwade/festival/pull/2515. I've also provided a minimal reproduction.

Here's the error:

```
TypeError: input.specifier.startsWith is not a function
    at file:///Users/stephen.wade/git/festival/node_modules/knip/dist/WorkspaceWorker.js:305:54
```

I've narrowed it down to one lint-staged command. The relevant part of the package.json file is this:

```json
  "devDependencies": {
    "knip": "^5.30.1",
    "lint-staged": "^16.2.7"
  },
  "lint-staged": {
    "prisma.schema": "prisma format --schema"
  }
```

If I change "prisma format --schema" in any way (change "--schema" to "--example", remove "--schema", change "prisma" to "example"), remove the "lint-staged" key, or remove the lint-staged dependency, the error stops happening.

`git bisect` narrows down the issue to this commit: 2d0bb0cd38fb8d0502532b0999cb4cf795c3e4cb.

### PR DESCRIPTION
**Pull request by stephenwade**
Fixes #1463.

Reproductions:
- https://stackblitz.com/edit/github-qrpmgdzo-zgascumc?file=package.json
- https://github.com/stephenwade/festival/pull/2515

### CODE REVIEW

**Comment by webpro** [comment]
Thanks Steven! Looks like that commit revealed the bug (using a boolean as a path).

**Comment by webpro** [comment]
:rocket: _This pull request is included in v5.81.0. See [Release 5.81.0](https://github.com/webpro-nl/knip/releases/tag/knip%405.81.0) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._
